// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    public partial class AccountMessage
    {
        [Key]
        public int Id { get; set; }
        public int? SenderId { get; set; }
        public int? RecieverId { get; set; }
        [Unicode(false)]
        public string Message { get; set; }
        public DateTime? Date { get; set; }
        public bool? Read { get; set; }
        public bool? Deleted { get; set; }

        [ForeignKey("RecieverId")]
        [InverseProperty("AccountMessageRecievers")]
        public virtual Account Reciever { get; set; }
        [ForeignKey("SenderId")]
        [InverseProperty("AccountMessageSenders")]
        public virtual Account Sender { get; set; }
    }
}