// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using IndexAttribute = Microsoft.EntityFrameworkCore.IndexAttribute;

namespace FreelancingTeamData.Models
{
    [Table("Account")]
    [Index("Username", Name = "UQ_Account_536C85E439D3FF98", IsUnique = true)]
    [Index("Email", Name = "UQ_Account_A9D10534F70C4439", IsUnique = true)]
    public partial class Account
    {
        public Account()
        {
            AccountMessageRecievers = new HashSet<AccountMessage>();
            AccountMessageSenders = new HashSet<AccountMessage>();
            UserConnections = new HashSet<UserConnection>();
            Notifications = new HashSet<Notification>();
        }

        [Key]
        public int Id { get; set; }
        public string? IdentityId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Username { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string LastName { get; set; }
        [Unicode(false)]
        public string Password { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Type { get; set; }

        [InverseProperty("IdNavigation")]
        public virtual Admin Admin { get; set; }
        [InverseProperty("IdNavigation")]
        public virtual User User { get; set; }
        [InverseProperty("Reciever")]
        public virtual ICollection<AccountMessage> AccountMessageRecievers { get; set; }
        [InverseProperty("Sender")]
        public virtual ICollection<AccountMessage> AccountMessageSenders { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserConnection> UserConnections { get; set; }

        [ForeignKey("AccountId")]
        [InverseProperty("Accounts")]
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}