// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Admin")]
    public partial class Admin
    {
        public Admin()
        {
            Clients = new HashSet<Client>();
            Complains = new HashSet<Complain>();
            Freelancers = new HashSet<Freelancer>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string FName { get; set; }
        [Required]
        public string LName { get; set; }
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }

        [InverseProperty("Admin")]
        public virtual ICollection<Client> Clients { get; set; }
        [InverseProperty("AdminHandler")]
        public virtual ICollection<Complain> Complains { get; set; }
        [InverseProperty("Admin")]
        public virtual ICollection<Freelancer> Freelancers { get; set; }
    }
}