// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Client")]
    public partial class Client
    {
        public Client()
        {
            ClientCredits = new HashSet<ClientCredit>();
            ClientLanguages = new HashSet<ClientLanguage>();
            ClientSendTransactionToTeams = new HashSet<ClientSendTransactionToTeam>();
            Complains = new HashSet<Complain>();
        }

        [Key]
        public int Id { get; set; }
        public double? Rate { get; set; }
        [Column(TypeName = "image")]
        public byte[] Image { get; set; }
        public int? ReplySpeed { get; set; }
        [Column(TypeName = "numeric(18, 0)")]
        public decimal? Phone { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Birthday { get; set; }
        public string Bio { get; set; }
        public bool? ActiveStatus { get; set; }
        public int? UserId { get; set; }
        public int? WalletId { get; set; }
        public int? AdminId { get; set; }
        public int? IdentityVerfication { get; set; }

        [ForeignKey("AdminId")]
        [InverseProperty("Clients")]
        public virtual Admin Admin { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("Clients")]
        public virtual UserAccount User { get; set; }
        [ForeignKey("WalletId")]
        [InverseProperty("Clients")]
        public virtual Wallet Wallet { get; set; }
        [InverseProperty("Client")]
        public virtual ICollection<ClientCredit> ClientCredits { get; set; }
        [InverseProperty("Client")]
        public virtual ICollection<ClientLanguage> ClientLanguages { get; set; }
        [InverseProperty("Client")]
        public virtual ICollection<ClientSendTransactionToTeam> ClientSendTransactionToTeams { get; set; }
        [InverseProperty("Client")]
        public virtual ICollection<Complain> Complains { get; set; }
    }
}