// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("ClientLanguage")]
    public partial class ClientLanguage
    {
        [Key]
        public int ClientId { get; set; }
        [Key]
        [StringLength(50)]
        public string Language { get; set; }

        [ForeignKey("ClientId")]
        [InverseProperty("ClientLanguages")]
        public virtual Client Client { get; set; }
    }
}