// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Complain")]
    public partial class Complain
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Description { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        public int? ComplainingUserId { get; set; }
        public int? ComplainingTeamId { get; set; }
        public int? AdminHandlerId { get; set; }

        [ForeignKey("AdminHandlerId")]
        [InverseProperty("Complains")]
        public virtual Admin AdminHandler { get; set; }
        [ForeignKey("ComplainingTeamId")]
        [InverseProperty("Complains")]
        public virtual Team ComplainingTeam { get; set; }
        [ForeignKey("ComplainingUserId")]
        [InverseProperty("Complains")]
        public virtual User ComplainingUser { get; set; }
    }
}