// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Complain")]
    public partial class Complain
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        public string Description { get; set; }
        public int? ClientId { get; set; }
        public int? FreelancerId { get; set; }
        public int? TeamId { get; set; }
        public int? AdminHandlerId { get; set; }

        [ForeignKey("AdminHandlerId")]
        [InverseProperty("Complains")]
        public virtual Admin AdminHandler { get; set; }
        [ForeignKey("ClientId")]
        [InverseProperty("Complains")]
        public virtual Client Client { get; set; }
        [ForeignKey("FreelancerId")]
        [InverseProperty("Complains")]
        public virtual Freelancer Freelancer { get; set; }
        [ForeignKey("TeamId")]
        [InverseProperty("Complains")]
        public virtual Team Team { get; set; }
    }
}