// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Deal")]
    public partial class Deal
    {
        [Key]
        public int ClientId { get; set; }
        [Key]
        public int TeamId { get; set; }
        [Key]
        public int ProjectId { get; set; }
        [Column(TypeName = "money")]
        public decimal? Money { get; set; }
        public int? Duration { get; set; }
        public bool? Done { get; set; }

        [ForeignKey("ClientId")]
        [InverseProperty("Deals")]
        public virtual Client Client { get; set; }
        [ForeignKey("ProjectId")]
        [InverseProperty("Deals")]
        public virtual Project Project { get; set; }
        [ForeignKey("TeamId")]
        [InverseProperty("Deals")]
        public virtual Team Team { get; set; }
    }
}