// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("FreelancerHasSkill")]
    public partial class FreelancerHasSkill
    {
        [Key]
        public int FreelancerId { get; set; }
        [Key]
        public int SkillId { get; set; }
        public double? EfficiancyRate { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("FreelancerHasSkills")]
        public virtual Freelancer Freelancer { get; set; }
        [ForeignKey("SkillId")]
        [InverseProperty("FreelancerHasSkills")]
        public virtual Skill Skill { get; set; }
    }
}