// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("FreelancerExperience")]
    public partial class FreelancerExperience
    {
        [Key]
        public int FreelancerId { get; set; }
        [Key]
        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? EndDate { get; set; }
        [StringLength(50)]
        public string JobTitle { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyName { get; set; }
        public bool? CurentllyWorking { get; set; }
        [StringLength(50)]
        public string JobKind { get; set; }
        public string Summary { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("FreelancerExperiences")]
        public virtual Freelancer Freelancer { get; set; }
    }
}