// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("FreelancerEducation")]
    public partial class FreelancerEducation
    {
        [Key]
        public int FreelancerId { get; set; }
        [Key]
        public int gradYear { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Grade { get; set; }
        [StringLength(50)]
        public string University { get; set; }
        [StringLength(50)]
        public string Faculty { get; set; }
        [StringLength(50)]
        public string Department { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("FreelancerEducations")]
        public virtual Freelancer Freelancer { get; set; }
    }
}