// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("FreelancerLanguage")]
    public partial class FreelancerLanguage
    {
        [Key]
        public int FreelancerId { get; set; }
        [Key]
        [StringLength(50)]
        public string Language { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("FreelancerLanguages")]
        public virtual Freelancer Freelancer { get; set; }
    }
}