// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("FreelancerJoinTeam")]
    public partial class FreelancerJoinTeam
    {
        [Key]
        public int FreelancerId { get; set; }
        [Key]
        public int TeamId { get; set; }
        public bool? AcceddAllowed { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("FreelancerJoinTeams")]
        public virtual Freelancer Freelancer { get; set; }
        [ForeignKey("TeamId")]
        [InverseProperty("FreelancerJoinTeams")]
        public virtual Team Team { get; set; }
    }
}