// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("FreelancerAccountBank")]
    public partial class FreelancerAccountBank
    {
        [Key]
        public int FreelancerId { get; set; }
        [Key]
        public int Account { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("FreelancerAccountBanks")]
        public virtual Freelancer Freelancer { get; set; }
    }
}