// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("FreelancerCertificate")]
    public partial class FreelancerCertificate
    {
        [Key]
        public int FreelancerId { get; set; }
        [Key]
        [StringLength(50)]
        public string Title { get; set; }
        public string Link { get; set; }
        [StringLength(50)]
        public string Organization { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        public string Description { get; set; }
        [Required]
        [StringLength(50)]
        public string Specialization { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("FreelancerCertificates")]
        public virtual Freelancer Freelancer { get; set; }
    }
}