// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("FreelancerCredit")]
    public partial class FreelancerCredit
    {
        [Key]
        public int FreelacerId { get; set; }
        [Key]
        public int CreditNumber { get; set; }

        [ForeignKey("FreelacerId")]
        [InverseProperty("FreelancerCredits")]
        public virtual Freelancer Freelacer { get; set; }
    }
}