// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Notification")]
    public partial class Notification
    {
        public Notification()
        {
            Accounts = new HashSet<Account>();
            Teams = new HashSet<Team>();
        }

        [Key]
        public int Id { get; set; }
        [Unicode(false)]
        public string Description { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string type { get; set; }
        public int? type_id { get; set; }
        public bool? Accepted { get; set; }
        public bool? Read { get; set; }
        public DateTime? Date { get; set; }

        [ForeignKey("NotificationId")]
        [InverseProperty("Notifications")]
        public virtual ICollection<Account> Accounts { get; set; }
        [ForeignKey("NotificationId")]
        [InverseProperty("Notifications")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}