// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Portoflio")]
    public partial class Portoflio
    {
        public Portoflio()
        {
            Skills = new HashSet<Skill>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        public string Description { get; set; }
        [StringLength(50)]
        public string Link { get; set; }
        public int FreelancerId { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("Portoflios")]
        public virtual Freelancer Freelancer { get; set; }

        [ForeignKey("PortoflioId")]
        [InverseProperty("Portoflios")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}