// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("ProjectPayment")]
    public partial class ProjectPayment
    {
        [Key]
        public int TransactionId { get; set; }
        [Key]
        public int ClientId { get; set; }
        [Key]
        public int ProjectId { get; set; }
        [Column(TypeName = "money")]
        public decimal? TransferredMoney { get; set; }
        [Column(TypeName = "money")]
        public decimal? RefundedMoney { get; set; }

        [ForeignKey("ClientId")]
        [InverseProperty("ProjectPayments")]
        public virtual Client Client { get; set; }
        [ForeignKey("ProjectId")]
        [InverseProperty("ProjectPayments")]
        public virtual Project Project { get; set; }
        [ForeignKey("TransactionId")]
        [InverseProperty("ProjectPayments")]
        public virtual Transaction Transaction { get; set; }
    }
}