// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Project")]
    public partial class Project
    {
        public Project()
        {
            ProjectHasReviews = new HashSet<ProjectHasReview>();
            TeamBidsProjects = new HashSet<TeamBidsProject>();
            Skills = new HashSet<Skill>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PostingDate { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        public int? State { get; set; }
        public double? AVGBid { get; set; }
        public string Description { get; set; }
        public string Duration { get; set; }
        [Column(TypeName = "money")]
        public decimal? BudgetFrom { get; set; }
        [Column(TypeName = "money")]
        public decimal? BudgetTo { get; set; }
        public int? TeamId { get; set; }

        [ForeignKey("TeamId")]
        [InverseProperty("Projects")]
        public virtual Team Team { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<ProjectHasReview> ProjectHasReviews { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<TeamBidsProject> TeamBidsProjects { get; set; }

        [ForeignKey("ProjectId")]
        [InverseProperty("Projects")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}