// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("ProjectHasReview")]
    public partial class ProjectHasReview
    {
        [Key]
        public int ProjectId { get; set; }
        [Key]
        public int ReviewId { get; set; }
        [StringLength(50)]
        public string Sender { get; set; }

        [ForeignKey("ProjectId")]
        [InverseProperty("ProjectHasReviews")]
        public virtual Project Project { get; set; }
        [ForeignKey("ReviewId")]
        [InverseProperty("ProjectHasReviews")]
        public virtual Review Review { get; set; }
    }
}