// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Review")]
    public partial class Review
    {
        public Review()
        {
            ProjectHasReviews = new HashSet<ProjectHasReview>();
        }

        [Key]
        public int Id { get; set; }
        public double? Rate { get; set; }
        public string Description { get; set; }

        [InverseProperty("Review")]
        public virtual ICollection<ProjectHasReview> ProjectHasReviews { get; set; }
    }
}