// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Skill")]
    public partial class Skill
    {
        public Skill()
        {
            FreelancerHasSkills = new HashSet<FreelancerHasSkill>();
            Categories = new HashSet<Category>();
            Portoflios = new HashSet<Portoflio>();
            Projects = new HashSet<Project>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("Skill")]
        public virtual ICollection<FreelancerHasSkill> FreelancerHasSkills { get; set; }

        [ForeignKey("SkillId")]
        [InverseProperty("Skills")]
        public virtual ICollection<Category> Categories { get; set; }
        [ForeignKey("SkillId")]
        [InverseProperty("Skills")]
        public virtual ICollection<Portoflio> Portoflios { get; set; }
        [ForeignKey("SkillId")]
        [InverseProperty("Skills")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}