// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Social")]
    public partial class Social
    {
        [Key]
        public int UserId { get; set; }
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string Type { get; set; }
        [Unicode(false)]
        public string Link { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Socials")]
        public virtual UserAccount User { get; set; }
    }
}