// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Team")]
    public partial class Team
    {
        public Team()
        {
            ClientSendTransactionToTeams = new HashSet<ClientSendTransactionToTeam>();
            Complains = new HashSet<Complain>();
            FreelancerJoinTeams = new HashSet<FreelancerJoinTeam>();
            FreelancerTeamTransactions = new HashSet<FreelancerTeamTransaction>();
            Projects = new HashSet<Project>();
            TeamBidsProjects = new HashSet<TeamBidsProject>();
            TeamLanguages = new HashSet<TeamLanguage>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "image")]
        public byte[] Logo { get; set; }
        [StringLength(50)]
        public string WebSite { get; set; }
        public bool? IsVerfied { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreationDate { get; set; }
        public string Description { get; set; }
        public double? Rate { get; set; }
        public int? LeaderId { get; set; }
        public int? WalletId { get; set; }

        [ForeignKey("LeaderId")]
        [InverseProperty("Teams")]
        public virtual Freelancer Leader { get; set; }
        [ForeignKey("WalletId")]
        [InverseProperty("Teams")]
        public virtual Wallet Wallet { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<ClientSendTransactionToTeam> ClientSendTransactionToTeams { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<Complain> Complains { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<FreelancerJoinTeam> FreelancerJoinTeams { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<FreelancerTeamTransaction> FreelancerTeamTransactions { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<Project> Projects { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<TeamBidsProject> TeamBidsProjects { get; set; }
        [InverseProperty("Team")]
        public virtual ICollection<TeamLanguage> TeamLanguages { get; set; }
    }
}