// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace FreelancingTeamData.Models
{
    [Table("TeamTransaction")]
    public partial class TeamTransaction
    {
        [Key]
        public int TeamId { get; set; }
        [Key]
        public int FreelancerId { get; set; }
        [Key]
        public int ProjectId { get; set; }
        public int? Percentage { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("TeamTransactions")]
        public virtual Freelancer Freelancer { get; set; }
        [ForeignKey("ProjectId")]
        [InverseProperty("TeamTransactions")]
        public virtual Project Project { get; set; }
        [ForeignKey("TeamId")]
        [InverseProperty("TeamTransactions")]
        public virtual Team Team { get; set; }

        public static implicit operator TeamTransaction(EntityEntry<TeamTransaction> v)
        {
            throw new NotImplementedException();
        }

        //public static implicit operator TeamTransaction(void v)
        //{
        //    throw new NotImplementedException();
        //}
    }
}