// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("TeamBidsProject")]
    public partial class TeamBidsProject
    {
        [Key]
        public int TeamId { get; set; }
        [Key]
        public int ProjectId { get; set; }
        public string Message { get; set; }
        [Column(TypeName = "money")]
        public decimal? Money { get; set; }
        [StringLength(50)]
        public string Duration { get; set; }

        [ForeignKey("ProjectId")]
        [InverseProperty("TeamBidsProjects")]
        public virtual Project Project { get; set; }
        [ForeignKey("TeamId")]
        [InverseProperty("TeamBidsProjects")]
        public virtual Team Team { get; set; }
    }
}