// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("TeamLanguage")]
    public partial class TeamLanguage
    {
        [Key]
        public int TeamId { get; set; }
        [Key]
        [StringLength(50)]
        public string Language { get; set; }

        [ForeignKey("TeamId")]
        [InverseProperty("TeamLanguages")]
        public virtual Team Team { get; set; }
    }
}