// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    public partial class TeamFreelancerMessage
    {
        [Key]
        public int Id { get; set; }
        public int? UserId { get; set; }
        public int? TeamId { get; set; }
        [Unicode(false)]
        public string Message { get; set; }
        public DateTime? Date { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string Sender { get; set; } // T or U
        public bool? Read { get; set; }
        public bool? Deleted { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("TeamFreelancerMessages")]
        public virtual User User { get; set; }
        [ForeignKey("TeamId")]
        [InverseProperty("TeamFreelancerMessages")]
        public virtual Team Team { get; set; }
    }
}