// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    public partial class TeamFreelancerMessage
    {
        [Key]
        public int Id { get; set; }
        public int? ClientId { get; set; }
        public int? TeamId { get; set; }
        [Unicode(false)]
        public string Message { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Date { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string Sender { get; set; }
        public bool? Read { get; set; }
        public bool? Deleted { get; set; }

        [ForeignKey("ClientId")]
        [InverseProperty("TeamFreelancerMessages")]
        public virtual Client Client { get; set; }
        [ForeignKey("TeamId")]
        [InverseProperty("TeamFreelancerMessages")]
        public virtual Team Team { get; set; }
    }
}