// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    public partial class TeamMember
    {
        [Key]
        public int TeamId { get; set; }
        [Key]
        public int FreelancerId { get; set; }
        public bool? AccessAllowed { get; set; }

        [ForeignKey("FreelancerId")]
        [InverseProperty("TeamMembers")]
        public virtual Freelancer Freelancer { get; set; }
        [ForeignKey("TeamId")]
        [InverseProperty("TeamMembers")]
        public virtual Team Team { get; set; }

        public static implicit operator List<object>(TeamMember v)
        {
            throw new NotImplementedException();
        }
    }
}