// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Transaction")]
    public partial class Transaction
    {
        public Transaction()
        {
            ProjectPayments = new HashSet<ProjectPayment>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "money")]
        public decimal Money { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [StringLength(50)]
        public string Method { get; set; }

        [InverseProperty("Transaction")]
        public virtual ICollection<ProjectPayment> ProjectPayments { get; set; }

    }
}