// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Transaction")]
    public partial class Transaction
    {
        public Transaction()
        {
            ClientSendTransactionToTeams = new HashSet<ClientSendTransactionToTeam>();
            FreelancerTeamTransactions = new HashSet<FreelancerTeamTransaction>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "money")]
        public decimal? Money { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Date { get; set; }
        [StringLength(50)]
        public string Method { get; set; }

        [InverseProperty("Transaction")]
        public virtual ICollection<ClientSendTransactionToTeam> ClientSendTransactionToTeams { get; set; }
        [InverseProperty("Transaction")]
        public virtual ICollection<FreelancerTeamTransaction> FreelancerTeamTransactions { get; set; }
    }
}