// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("UserCredit")]
    public partial class UserCredit
    {
        [Key]
        public int UserId { get; set; }
        [Key]
        public int CreditNumber { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("UserCredits")]
        public virtual User User { get; set; }
    }
}