// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("UserAccount")]
    public partial class UserAccount
    {
        public UserAccount()
        {
            Clients = new HashSet<Client>();
            Freelancers = new HashSet<Freelancer>();
            Socials = new HashSet<Social>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [Unicode(false)]
        public string FName { get; set; }
        [Required]
        [Unicode(false)]
        public string LName { get; set; }
        [Required]
        [Unicode(false)]
        public string Email { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RegisterDate { get; set; }
        [Unicode(false)]
        public string Status { get; set; }
        [Required]
        [Unicode(false)]
        public string Password { get; set; }
        [Unicode(false)]
        public string Country { get; set; }
        [Unicode(false)]
        public string State { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<Client> Clients { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Freelancer> Freelancers { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Social> Socials { get; set; }
    }
}