// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("User")]
    public partial class User
    {
        public User()
        {
            Complains = new HashSet<Complain>();
            UserCredits = new HashSet<UserCredit>();
            UserLanguages = new HashSet<UserLanguage>();
            UserSocials = new HashSet<UserSocial>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime? BirthDate { get; set; }
        public int? ReplySpeed { get; set; }
        [Column(TypeName = "numeric(18, 0)")]
        public decimal? Phone { get; set; }
        [Column(TypeName = "date")]
        public DateTime? RegisterDate { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Country { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string State { get; set; }
        [Column(TypeName = "image")]
        public byte[] Image { get; set; }
        public double? Rate { get; set; }
        public bool? ActiveStatus { get; set; }
        public string Bio { get; set; }
        public bool? Client { get; set; }
        public bool? Freelancer { get; set; }
        public int? AdminValidated { get; set; }
        public int? WalletId { get; set; }
        public bool? Validated { get; set; }

        [ForeignKey("AdminValidated")]
        [InverseProperty("Users")]
        public virtual Admin AdminValidatedNavigation { get; set; }
        [ForeignKey("Id")]
        [InverseProperty("User")]
        public virtual Account IdNavigation { get; set; }
        [ForeignKey("WalletId")]
        [InverseProperty("Users")]
        public virtual Wallet Wallet { get; set; }
        [InverseProperty("IdNavigation")]
        public virtual Client ClientNavigation { get; set; }
        [InverseProperty("IdNavigation")]
        public virtual Freelancer FreelancerNavigation { get; set; }
        [InverseProperty("ComplainingUser")]
        public virtual ICollection<Complain> Complains { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserCredit> UserCredits { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserLanguage> UserLanguages { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserSocial> UserSocials { get; set; }
    }
}