// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FreelancingTeamData.Models
{
    [Table("Wallet")]
    public partial class Wallet
    {
        public Wallet()
        {
            Clients = new HashSet<Client>();
            Freelancers = new HashSet<Freelancer>();
            Teams = new HashSet<Team>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "money")]
        public decimal? Money { get; set; }
        [Column(TypeName = "money")]
        public decimal? Available { get; set; }

        [InverseProperty("Wallet")]
        public virtual ICollection<Client> Clients { get; set; }
        [InverseProperty("Wallet")]
        public virtual ICollection<Freelancer> Freelancers { get; set; }
        [InverseProperty("Wallet")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}